name: Go
on: [push, pull_request]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
          cache: true

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: zig test and build
        run: |
          make test
          make build
          make release-build
